# === File: netlify.toml (project root) ===
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"  # 启动 Vite 开发服务器
  targetPort = 5173        # Vite 本地端口
  port = 8888              # Netlify Dev 代理端口（默认）
  framework = "#custom"    # 明确使用自定义命令

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

