BEGIN;

-- 插入bars表数�?INSERT INTO public.bars (name, district_id, description, cash_only, card_accepted) VALUES
    ('momotaro tavern', 1, '评分 4.5/5 (2555 条评�? | 2 | 类型: establishment, food, point_of_interest, restaurant', false, false),
    ('Hops & Barley', 1, '评分 4.6/5 (821 条评�? | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Privatbrauerei Schalander', 1, '评分 4.5/5 (593 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Schlossplatzbrauerei Köpenick', 1, '评分 4.4/5 (1437 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Brauhaus Neulich GmbH', 1, '评分 4.6/5 (780 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Protokoll Taproom', 1, '评分 4.7/5 (1857 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Straßenbräu', 1, '评分 4.6/5 (790 条评�? | 3 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biererei Bar & Vintage Cellar', 1, '评分 4.8/5 (1180 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Berlin Craft Beer Experience', 1, '评分 4.6/5 (85 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant, travel_agency', false, false),
    ('Leibhaftig', 1, '评分 4.5/5 (521 条评�? | 2 | 类型: bar, establishment, food, lodging, point_of_interest, restaurant', false, false),
    ('BKK Bier Kombinat Kreuzberg', 1, '评分 4.6/5 (167 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Craftcore Brewing & Unverhopft @Bar Amélie', 1, '评分 4.3/5 (71 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('SCHOPPE BRÄU TAPROOM im BKK', 1, '评分 4.4/5 (128 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Vagabund Brauerei Kesselhaus', 1, '评分 4.5/5 (239 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('BrewDog Berlin Friedrichshain', 1, '评分 3.7/5 (1259 条评�? | 2 | 类型: bar, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('Straßenbräu Brewery', 1, '评分 4.9/5 (7 条评�? | 类型: establishment, food, point_of_interest', false, false),
    ('Marcus Brewery Berlin', 1, '评分 3.8/5 (611 条评�? | 2 | 类型: establishment, food, point_of_interest, restaurant', false, false),
    ('Lemke am Schloss', 1, '评分 4.3/5 (2680 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt', 1, '评分 4.5/5 (2177 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Mauerwerk', 1, '评分 4.6/5 (684 条评�? | 2 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Lindenbräu am Potsdamer Platz', 1, '评分 4.1/5 (4878 条评�? | 3 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('HERMAN Belgian Bar', 1, '评分 4.6/5 (1148 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Schneeeule Salon für Berliner Bierkultur', 1, '评分 4.8/5 (205 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Birra - Italian Craft Beer', 1, '评分 4.7/5 (1271 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Bierhaus Urban', 1, '评分 4.4/5 (805 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Manifest Taproom', 1, '评分 4.6/5 (593 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Das Haus der 100 Biere -Deutsches Restaurant und Bar', 1, '评分 4.2/5 (1925 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('HOME Bar', 1, '评分 4.6/5 (696 条评�? | 2 | 类型: bar, establishment, liquor_store, point_of_interest, store', false, false),
    ('Bier Laden Berlin', 1, '评分 4.7/5 (447 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('Berliner Bier-Akademie', 1, '评分 4.4/5 (568 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Bier Bar', 1, '评分 4.7/5 (250 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('k_eins - authentic wine & craft beer', 1, '评分 4.9/5 (76 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, store', false, false),
    ('FOERSTERS FEINE BIERE', 1, '评分 4.7/5 (380 条评�? | 2 | 类型: bar, establishment, liquor_store, point_of_interest, store', false, false),
    ('Das Gift', 1, '评分 4.3/5 (673 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('East - Korean Chicken Craft Beer Bar & Restaurant', 1, '评分 4/5 (383 条评�? | 2 | 类型: establishment, food, point_of_interest, restaurant', false, false),
    ('swart Bier & Weinlokal', 1, '评分 4.8/5 (205 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Craft Beer', 1, '类型: bar, establishment, point_of_interest', false, false),
    ('Sportsbar Tor 133', 1, '评分 4.2/5 (560 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('FC Magnet Bar', 1, '评分 4.3/5 (610 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Country Cheers / Sky-Sportsbar', 1, '评分 4.1/5 (242 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Salamas Bar', 1, '评分 4.5/5 (238 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Sportsbar Lolly-Pub', 1, '评分 4.5/5 (292 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Sky Kneipe Schöneberg Bei Joschi', 1, '评分 4.3/5 (307 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Schmittz', 1, '评分 4.3/5 (1410 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Veritas', 1, '评分 3.9/5 (237 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Bar11', 1, '评分 4.6/5 (351 条评�? | 1 | 类型: bar, establishment, point_of_interest', false, false),
    ('Sportsbar Libero', 1, '评分 4.6/5 (159 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Sportbar', 1, '评分 4.5/5 (2 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Tante Käthe', 1, '评分 4.5/5 (538 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Sky Sportsbar Ducky''s Kneipe', 1, '评分 3.8/5 (188 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false);

-- 插入bar_locations表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'momotaro tavern',
        'Hops & Barley',
        'Privatbrauerei Schalander',
        'Schlossplatzbrauerei Köpenick',
        'Brauhaus Neulich GmbH',
        'Protokoll Taproom',
        'Straßenbräu',
        'Biererei Bar & Vintage Cellar',
        'Berlin Craft Beer Experience',
        'Leibhaftig',
        'BKK Bier Kombinat Kreuzberg',
        'Craftcore Brewing & Unverhopft @Bar Amélie',
        'SCHOPPE BRÄU TAPROOM im BKK',
        'Vagabund Brauerei Kesselhaus',
        'BrewDog Berlin Friedrichshain',
        'Straßenbräu Brewery',
        'Marcus Brewery Berlin',
        'Lemke am Schloss',
        'Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt',
        'Mauerwerk',
        'Lindenbräu am Potsdamer Platz',
        'HERMAN Belgian Bar',
        'Schneeeule Salon für Berliner Bierkultur',
        'Birra - Italian Craft Beer',
        'Bierhaus Urban',
        'Manifest Taproom',
        'Das Haus der 100 Biere -Deutsches Restaurant und Bar',
        'HOME Bar',
        'Bier Laden Berlin',
        'Berliner Bier-Akademie',
        'Bier Bar',
        'k_eins - authentic wine & craft beer',
        'FOERSTERS FEINE BIERE',
        'Das Gift',
        'East - Korean Chicken Craft Beer Bar & Restaurant',
        'swart Bier & Weinlokal',
        'Craft Beer',
        'Sportsbar Tor 133',
        'FC Magnet Bar',
        'Country Cheers / Sky-Sportsbar',
        'Salamas Bar',
        'Sportsbar Lolly-Pub',
        'Sky Kneipe Schöneberg Bei Joschi',
        'Schmittz',
        'Veritas',
        'Bar11',
        'Sportsbar Libero',
        'Sportbar',
        'Tante Käthe',
        'Sky Sportsbar Ducky''s Kneipe'
    )
)
INSERT INTO public.bar_locations (bar_id, address_line, postal_code, latitude, longitude)
SELECT ib.id, loc.address_line, loc.postal_code, loc.latitude, loc.longitude
FROM inserted_bars ib
JOIN (VALUES
    ('momotaro tavern', 'Panoramastraße 1A, 10178 Berlin, Germany', '10178', 52.5209983, 13.4090925),
    ('Hops & Barley', 'Wühlischstraße 22/23, 10245 Berlin, Germany', '10245', 52.5089972, 13.4606998),
    ('Privatbrauerei Schalander', 'Revaler Str. 99/haus 9, 10245 Berlin, Germany', '10245', 52.507079, 13.456801),
    ('Schlossplatzbrauerei Köpenick', 'Grünstraße 24, 12555 Berlin, Germany', '12555', 52.44462, 13.5744228),
    ('Brauhaus Neulich GmbH', 'Selchower Str. 20, 12049 Berlin, Germany', '12049', 52.4784257, 13.4199255),
    ('Protokoll Taproom', 'Boxhagener Str. 110, 10245 Berlin, Germany', '10245', 52.5131501, 13.4570661),
    ('Straßenbräu', 'Neue Bahnhofstraße 30, 10245 Berlin, Germany', '10245', 52.5055415, 13.4693127),
    ('Biererei Bar & Vintage Cellar', 'Oranienstraße 185, 10999 Berlin, Germany', '10999', 52.500657, 13.421101),
    ('Berlin Craft Beer Experience', 'Frankfurter Allee 43, 10247 Berlin, Germany', '10247', 52.5151282, 13.4632389),
    ('Leibhaftig', 'Metzer Str. 30, 10405 Berlin, Germany', '10405', 52.5315884, 13.4170381),
    ('BKK Bier Kombinat Kreuzberg', 'Manteuffelstraße 53, 10999 Berlin, Germany', '10999', 52.4977326, 13.4247369),
    ('Craftcore Brewing & Unverhopft @Bar Amélie', 'Bar Amelie, Auguststraße 2, 10117 Berlin, Germany', '10117', 52.5258365, 13.3907872),
    ('SCHOPPE BRÄU TAPROOM im BKK', 'Manteuffelstraße 53, 10999 Berlin, Germany', '10999', 52.49774900000001, 13.424725),
    ('Vagabund Brauerei Kesselhaus', 'Oudenarder Str. 16-20, 13347 Berlin, Germany', '13347', 52.5530096, 13.359492),
    ('BrewDog Berlin Friedrichshain', 'Frankfurter Tor 7, 10243 Berlin, Germany', '10243', 52.5151262, 13.4543451),
    ('Straßenbräu Brewery', 'Zur Alten Börse 72-74, 12681 Berlin, Germany', '12681', 52.5203423, 13.5268971),
    ('Marcus Brewery Berlin', 'Münzstraße 1-3, 10178 Berlin, Germany', '10178', 52.523963, 13.409178),
    ('Lemke am Schloss', 'Luisenpl. 1, 10585 Berlin, Germany', '10585', 52.5199784, 13.2998062),
    ('Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt', 'Direkt neben dem Maritim proArte Hotel, Dorotheenstraße 65, 10117 Berlin, Germany', '10117', 52.5184794, 13.3867795),
    ('Mauerwerk', 'Zwinglistraße 7, 10555 Berlin, Germany', '10555', 52.52563199999999, 13.3329329),
    ('Lindenbräu am Potsdamer Platz', 'Bellevuestraße 3-5, 10785 Berlin, Germany', '10785', 52.5102081, 13.3728723),
    ('HERMAN Belgian Bar', 'Schönhauser Allee 173, 10119 Berlin, Germany', '10119', 52.53240419999999, 13.4121625),
    ('Schneeeule Salon für Berliner Bierkultur', 'Ofener Str. 1, 13349 Berlin, Germany', '13349', 52.5553102, 13.3441805),
    ('Birra - Italian Craft Beer', 'Prenzlauer Allee 198, 10405 Berlin, Germany', '10405', 52.5386191, 13.4234473),
    ('Bierhaus Urban', 'Urbanstraße 126, 10967 Berlin, Germany', '10967', 52.4912256, 13.4161159),
    ('Manifest Taproom', 'Oderberger Str. 15, 10435 Berlin, Germany', '10435', 52.5393294, 13.4084481),
    ('Das Haus der 100 Biere -Deutsches Restaurant und Bar', 'Kurfürstendamm 100, 10709 Berlin, Germany', '10709', 52.4984045, 13.2970996),
    ('HOME Bar', 'Neue Bahnhofstraße 23, 10245 Berlin, Germany', '10245', 52.507129, 13.4708367),
    ('Bier Laden Berlin', 'Kreuzbergstraße 78, 10965 Berlin, Germany', '10965', 52.4897317, 13.3855758),
    ('Berliner Bier-Akademie', 'Fürther Str. 8, 10777 Berlin, Germany', '10777', 52.49830189999999, 13.3352162),
    ('Bier Bar', 'Kopernikusstraße 9, 10245 Berlin, Germany', '10245', 52.5104775, 13.4527095),
    ('k_eins - authentic wine & craft beer', 'Kopenhagener Str. 1, 10437 Berlin, Germany', '10437', 52.5488563, 13.4128888),
    ('FOERSTERS FEINE BIERE', 'Bornstraße 20, 12163 Berlin, Germany', '12163', 52.4665682, 13.3219215),
    ('Das Gift', 'Donaustraße 119, 12043 Berlin, Germany', '12043', 52.484075, 13.4324361),
    ('East - Korean Chicken Craft Beer Bar & Restaurant', 'Heiligegeistkirchplatz 1, 10178 Berlin, Germany', '10178', 52.5204429, 13.4030727),
    ('swart Bier & Weinlokal', 'Dreysestraße 17, 10559 Berlin, Germany', '10559', 52.52810479999999, 13.3527465),
    ('Craft Beer', '10247 Berlin, Germany', '10247', 52.5148082, 13.4620716),
    ('Sportsbar Tor 133', 'Torstraße 133, 10119 Berlin, Germany', '10119', 52.5297324, 13.3997225),
    ('FC Magnet Bar', 'Veteranenstraße 26, 10119 Berlin, Germany', '10119', 52.5329778, 13.3999833),
    ('Country Cheers / Sky-Sportsbar', 'Karl-Marx-Allee 65, 10243 Berlin, Germany', '10243', 52.5184661, 13.4322259),
    ('Salamas Bar', 'Niederbarnimstraße 24, 10247 Berlin, Germany', '10247', 52.5143025, 13.4596994),
    ('Sportsbar Lolly-Pub', 'Bänschstraße 54, 10247 Berlin, Germany', '10247', 52.5179524, 13.465691),
    ('Sky Kneipe Schöneberg Bei Joschi', 'Grunewaldstraße 39, 10825 Berlin, Germany', '10825', 52.48936089999999, 13.3447285),
    ('Schmittz', 'Gormannstraße 19, 10119 Berlin, Germany', '10119', 52.5293112, 13.4052558),
    ('Veritas', 'Krumme Str. 50, 10627 Berlin, Germany', '10627', 52.5058173, 13.3090232),
    ('Bar11', 'Wiener Str. 21, 10999 Berlin, Germany', '10999', 52.4974, 13.43116),
    ('Sportsbar Libero', 'Karl-Lade-Straße 30, 10369 Berlin, Germany', '10369', 52.5288657, 13.4641261),
    ('Sportbar', 'Warschauer Str. 79, 10243 Berlin, Germany', '10243', 52.5134795, 13.4534341),
    ('Tante Käthe', 'Bernauer Str. 63-64, 13355 Berlin, Germany', '13355', 52.5404135, 13.4030038),
    ('Sky Sportsbar Ducky''s Kneipe', 'Mariendorfer Damm 112, 12109 Berlin, Germany', '12109', 52.4422673, 13.3862458)
) AS loc(name, address_line, postal_code, latitude, longitude) ON ib.name = loc.name;

-- 插入bar_themes表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'momotaro tavern',
        'Hops & Barley',
        'Privatbrauerei Schalander',
        'Schlossplatzbrauerei Köpenick',
        'Brauhaus Neulich GmbH',
        'Protokoll Taproom',
        'Straßenbräu',
        'Biererei Bar & Vintage Cellar',
        'Berlin Craft Beer Experience',
        'Leibhaftig',
        'BKK Bier Kombinat Kreuzberg',
        'Craftcore Brewing & Unverhopft @Bar Amélie',
        'SCHOPPE BRÄU TAPROOM im BKK',
        'Vagabund Brauerei Kesselhaus',
        'BrewDog Berlin Friedrichshain',
        'Straßenbräu Brewery',
        'Marcus Brewery Berlin',
        'Lemke am Schloss',
        'Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt',
        'Mauerwerk',
        'Lindenbräu am Potsdamer Platz',
        'HERMAN Belgian Bar',
        'Schneeeule Salon für Berliner Bierkultur',
        'Birra - Italian Craft Beer',
        'Bierhaus Urban',
        'Manifest Taproom',
        'Das Haus der 100 Biere -Deutsches Restaurant und Bar',
        'HOME Bar',
        'Bier Laden Berlin',
        'Berliner Bier-Akademie',
        'Bier Bar',
        'k_eins - authentic wine & craft beer',
        'FOERSTERS FEINE BIERE',
        'Das Gift',
        'East - Korean Chicken Craft Beer Bar & Restaurant',
        'swart Bier & Weinlokal',
        'Craft Beer',
        'Sportsbar Tor 133',
        'FC Magnet Bar',
        'Country Cheers / Sky-Sportsbar',
        'Salamas Bar',
        'Sportsbar Lolly-Pub',
        'Sky Kneipe Schöneberg Bei Joschi',
        'Schmittz',
        'Veritas',
        'Bar11',
        'Sportsbar Libero',
        'Sportbar',
        'Tante Käthe',
        'Sky Sportsbar Ducky''s Kneipe'
    )
)
INSERT INTO public.bar_themes (bar_id, theme_id)
SELECT ib.id, t.id
FROM inserted_bars ib
JOIN (VALUES
    ('momotaro tavern', 'cocktails'),
    ('momotaro tavern', 'food'),
    ('Hops & Barley', 'cocktails'),
    ('Hops & Barley', 'food'),
    ('Privatbrauerei Schalander', 'cocktails'),
    ('Privatbrauerei Schalander', 'food'),
    ('Schlossplatzbrauerei Köpenick', 'cocktails'),
    ('Schlossplatzbrauerei Köpenick', 'food'),
    ('Brauhaus Neulich GmbH', 'cocktails'),
    ('Protokoll Taproom', 'cocktails'),
    ('Straßenbräu', 'cocktails'),
    ('Straßenbräu', 'food'),
    ('Biererei Bar & Vintage Cellar', 'cocktails'),
    ('Berlin Craft Beer Experience', 'cocktails'),
    ('Berlin Craft Beer Experience', 'food'),
    ('Leibhaftig', 'cocktails'),
    ('Leibhaftig', 'food'),
    ('BKK Bier Kombinat Kreuzberg', 'cocktails'),
    ('Craftcore Brewing & Unverhopft @Bar Amélie', 'cocktails'),
    ('Craftcore Brewing & Unverhopft @Bar Amélie', 'food'),
    ('SCHOPPE BRÄU TAPROOM im BKK', 'cocktails'),
    ('SCHOPPE BRÄU TAPROOM im BKK', 'food'),
    ('Vagabund Brauerei Kesselhaus', 'cocktails'),
    ('Vagabund Brauerei Kesselhaus', 'food'),
    ('BrewDog Berlin Friedrichshain', 'cocktails'),
    ('BrewDog Berlin Friedrichshain', 'food'),
    ('BrewDog Berlin Friedrichshain', 'spirits'),
    ('Straßenbräu Brewery', 'cocktails'),
    ('Straßenbräu Brewery', 'food'),
    ('Marcus Brewery Berlin', 'cocktails'),
    ('Marcus Brewery Berlin', 'food'),
    ('Lemke am Schloss', 'cocktails'),
    ('Lemke am Schloss', 'food'),
    ('Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt', 'cocktails'),
    ('Gaffel Haus Berlin - Das Kölsche Konsulat in der Hauptstadt', 'food'),
    ('Mauerwerk', 'cocktails'),
    ('Mauerwerk', 'food'),
    ('Mauerwerk', 'spirits'),
    ('Lindenbräu am Potsdamer Platz', 'cocktails'),
    ('Lindenbräu am Potsdamer Platz', 'food'),
    ('HERMAN Belgian Bar', 'cocktails'),
    ('Schneeeule Salon für Berliner Bierkultur', 'cocktails'),
    ('Schneeeule Salon für Berliner Bierkultur', 'food'),
    ('Birra - Italian Craft Beer', 'cocktails'),
    ('Birra - Italian Craft Beer', 'food'),
    ('Bierhaus Urban', 'cocktails'),
    ('Manifest Taproom', 'cocktails'),
    ('Manifest Taproom', 'food'),
    ('Das Haus der 100 Biere -Deutsches Restaurant und Bar', 'cocktails'),
    ('Das Haus der 100 Biere -Deutsches Restaurant und Bar', 'food'),
    ('HOME Bar', 'cocktails'),
    ('HOME Bar', 'spirits'),
    ('Bier Laden Berlin', 'cocktails'),
    ('Bier Laden Berlin', 'food'),
    ('Bier Laden Berlin', 'spirits'),
    ('Berliner Bier-Akademie', 'cocktails'),
    ('Bier Bar', 'cocktails'),
    ('k_eins - authentic wine & craft beer', 'cocktails'),
    ('k_eins - authentic wine & craft beer', 'food'),
    ('k_eins - authentic wine & craft beer', 'spirits'),
    ('FOERSTERS FEINE BIERE', 'cocktails'),
    ('FOERSTERS FEINE BIERE', 'spirits'),
    ('Das Gift', 'cocktails'),
    ('East - Korean Chicken Craft Beer Bar & Restaurant', 'cocktails'),
    ('East - Korean Chicken Craft Beer Bar & Restaurant', 'food'),
    ('swart Bier & Weinlokal', 'cocktails'),
    ('Craft Beer', 'cocktails'),
    ('Sportsbar Tor 133', 'cocktails'),
    ('Sportsbar Tor 133', 'food'),
    ('FC Magnet Bar', 'cocktails'),
    ('FC Magnet Bar', 'food'),
    ('Country Cheers / Sky-Sportsbar', 'cocktails'),
    ('Salamas Bar', 'cocktails'),
    ('Sportsbar Lolly-Pub', 'cocktails'),
    ('Sportsbar Lolly-Pub', 'food'),
    ('Sky Kneipe Schöneberg Bei Joschi', 'cocktails'),
    ('Schmittz', 'cocktails'),
    ('Veritas', 'cocktails'),
    ('Veritas', 'food'),
    ('Bar11', 'cocktails'),
    ('Sportsbar Libero', 'cocktails'),
    ('Sportbar', 'cocktails'),
    ('Tante Käthe', 'cocktails'),
    ('Sky Sportsbar Ducky''s Kneipe', 'cocktails'),
    ('Sky Sportsbar Ducky''s Kneipe', 'food')
) AS bt(bar_name, theme_name) ON ib.name = bt.bar_name
JOIN public.themes t ON t.name = bt.theme_name;

COMMIT;

-- 批次 8: 记录 351-400
