BEGIN;

-- 插入bars表数�?INSERT INTO public.bars (name, district_id, description, cash_only, card_accepted) VALUES
    ('Cassiopeia Sommergarten', 1, '评分 4.5/5 (641 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Weihenstephaner Berlin', 1, '评分 4/5 (2783 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Holzmarkt 25', 1, '评分 4.7/5 (11753 条评�? | 2 | 类型: bar, establishment, food, night_club, park, point_of_interest, restaurant', false, false),
    ('Bier & Garten JamesHobrecht', 1, '评分 4.5/5 (282 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Wannseeterrassen Berlin', 1, '评分 4.2/5 (2004 条评�? | 3 | 类型: bar, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Biergarten Strandbar Berlista', 1, '评分 4.7/5 (28 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Fischerhütte am Schlachtensee', 1, '评分 3.5/5 (4047 条评�? | 3 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biergarten am Kleinen Tiergarten', 1, '评分 4.4/5 (206 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('NAUMANNS Biergarten', 1, '评分 4.3/5 (317 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Aquino Sommergarten', 1, '评分 5/5 (3 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Mauersegler Berlin', 1, '评分 4.3/5 (1189 条评�? | 2 | 类型: bar, establishment, food, night_club, point_of_interest, restaurant', false, false),
    ('Biergarten am Schlachtensee', 1, '评分 3.7/5 (596 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Landhaus Schupke', 1, '评分 4.6/5 (854 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Bootshaus Sportdenkmal', 1, '评分 4.7/5 (502 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Brauhaus Spandau', 1, '评分 4.3/5 (2479 条评�? | 2 | 类型: bar, establishment, food, liquor_store, lodging, point_of_interest, restaurant, store', false, false),
    ('Biergarten Jockel', 1, '评分 4.1/5 (1286 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biergarten auf der Insel der Jugend', 1, '评分 4/5 (39 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Eschenbräu', 1, '评分 4.6/5 (1344 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Tiergarten-Quelle', 1, '评分 4.5/5 (3552 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biergarten - Freiheit', 1, '评分 4.5/5 (361 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('CapRivi', 1, '评分 4.3/5 (913 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Teehaus im Englischen Garten Berlin', 1, '评分 4.2/5 (3051 条评�? | 2 | 类型: bar, establishment, food, park, point_of_interest, restaurant', false, false),
    ('Banja Luka', 1, '评分 4.2/5 (604 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Südblock', 1, '评分 4.4/5 (2137 条评�? | 1 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant', false, false),
    ('Die Laube Biergarten', 1, '评分 4.3/5 (427 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Sommergarten am FaF', 1, '评分 4/5 (30 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Bierhof Rüdersdorf', 1, '评分 4.4/5 (247 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Babette''s Garten', 1, '评分 4.4/5 (23 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Zur Gerichtslaube', 1, '评分 4.4/5 (4612 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Kulturhaus Insel Berlin', 1, '评分 4.4/5 (1891 条评�? | 2 | 类型: bar, establishment, food, meal_takeaway, point_of_interest, restaurant', false, false),
    ('Rosengarten Kulturpavillon', 1, '评分 4.5/5 (426 条评�? | 类型: bar, cafe, establishment, food, point_of_interest, restaurant', false, false),
    ('Bergterrasse Marienhöhe', 1, '评分 4/5 (234 条评�? | 1 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant', false, false),
    ('Sommergarten Jungfernheide', 1, '评分 4.5/5 (768 条评�? | 2 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Emma & Paul''s Biergarten / Eiskrem Hausgemacht', 1, '评分 4.5/5 (1560 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Biergarten Rudower Höhe bei Käse Paul', 1, '评分 4.5/5 (195 条评�? | 1 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biergarten der Tiergartenquelle', 1, '评分 4.4/5 (35 条评�? | 类型: establishment, food, point_of_interest, restaurant', false, false),
    ('Zosse �?Bar / Biergarten', 1, '评分 4.8/5 (530 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Kulturbiergarten Jungfernheide', 1, '评分 4.3/5 (610 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('FISHERMANS SeeGarten', 1, '评分 4.3/5 (514 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Biergarten am Herthasee', 1, '评分 4.3/5 (198 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Alte Turnhalle', 1, '评分 4.7/5 (3630 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 1, '评分 4.8/5 (39 条评�? | 类型: bar, cafe, establishment, food, meal_takeaway, night_club, point_of_interest, restaurant, store', false, false),
    ('South Beer Garden', 1, '评分 3.7/5 (376 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('White Lounge Shisha', 1, '评分 4.8/5 (3659 条评�? | 2 | 类型: cafe, establishment, food, point_of_interest, restaurant', false, false),
    ('11n Lounge', 1, '评分 4.4/5 (1984 条评�? | 1 | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('BER Lounge Tempelhof', 1, '评分 3.8/5 (659 条评�? | 类型: establishment, point_of_interest', false, false),
    ('DB Lounge Berlin Hbf', 1, '评分 4/5 (604 条评�? | 1 | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('PanAm Lounge', 1, '评分 4.7/5 (293 条评�? | 类型: establishment, point_of_interest', false, false),
    ('BER Lounge Tegel', 1, '评分 3.2/5 (217 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Floating Lounge at Shipotel', 1, '评分 4.4/5 (428 条评�? | 1 | 类型: bar, establishment, night_club, point_of_interest', false, false);

-- 插入bar_locations表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'Cassiopeia Sommergarten',
        'Weihenstephaner Berlin',
        'Holzmarkt 25',
        'Bier & Garten JamesHobrecht',
        'Wannseeterrassen Berlin',
        'Biergarten Strandbar Berlista',
        'Fischerhütte am Schlachtensee',
        'Biergarten am Kleinen Tiergarten',
        'NAUMANNS Biergarten',
        'Aquino Sommergarten',
        'Mauersegler Berlin',
        'Biergarten am Schlachtensee',
        'Landhaus Schupke',
        'Bootshaus Sportdenkmal',
        'Brauhaus Spandau',
        'Biergarten Jockel',
        'Biergarten auf der Insel der Jugend',
        'Eschenbräu',
        'Tiergarten-Quelle',
        'Biergarten - Freiheit',
        'CapRivi',
        'Teehaus im Englischen Garten Berlin',
        'Banja Luka',
        'Südblock',
        'Die Laube Biergarten',
        'Sommergarten am FaF',
        'Bierhof Rüdersdorf',
        'Babette''s Garten',
        'Zur Gerichtslaube',
        'Kulturhaus Insel Berlin',
        'Rosengarten Kulturpavillon',
        'Bergterrasse Marienhöhe',
        'Sommergarten Jungfernheide',
        'Emma & Paul''s Biergarten / Eiskrem Hausgemacht',
        'Biergarten Rudower Höhe bei Käse Paul',
        'Biergarten der Tiergartenquelle',
        'Zosse �?Bar / Biergarten',
        'Kulturbiergarten Jungfernheide',
        'FISHERMANS SeeGarten',
        'Biergarten am Herthasee',
        'Alte Turnhalle',
        'Karibik Berlin Köpenick - Strandbar und Biergarten',
        'South Beer Garden',
        'White Lounge Shisha',
        '11n Lounge',
        'BER Lounge Tempelhof',
        'DB Lounge Berlin Hbf',
        'PanAm Lounge',
        'BER Lounge Tegel',
        'Floating Lounge at Shipotel'
    )
)
INSERT INTO public.bar_locations (bar_id, address_line, postal_code, latitude, longitude)
SELECT ib.id, loc.address_line, loc.postal_code, loc.latitude, loc.longitude
FROM inserted_bars ib
JOIN (VALUES
    ('Cassiopeia Sommergarten', 'Revaler Str. 99, 10245 Berlin, Germany', '10245', 52.5068744, 13.4543832),
    ('Weihenstephaner Berlin', 'Neue Promenade 5, 10178 Berlin, Germany', '10178', 52.5230114, 13.4016676),
    ('Holzmarkt 25', 'Holzmarktstraße 25, 10243 Berlin, Germany', '10243', 52.5113137, 13.4268387),
    ('Bier & Garten JamesHobrecht', 'Hobrechtsfelder Dorfstraße 30 a, 16341 Panketal, Germany', '16341', 52.6666357, 13.4939201),
    ('Wannseeterrassen Berlin', 'Wannseebadweg 35, 14129 Berlin, Germany', '14129', 52.4414162, 13.178342),
    ('Biergarten Strandbar Berlista', 'Saatwinkler Damm 80, 13627 Berlin, Germany', '13627', 52.5482844, 13.2950372),
    ('Fischerhütte am Schlachtensee', 'Fischerhüttenstraße 136, 14163 Berlin, Germany', '14163', 52.4451587, 13.2275806),
    ('Biergarten am Kleinen Tiergarten', 'Alt-Moabit 25, 10559 Berlin, Germany', '10559', 52.5249958, 13.3484577),
    ('NAUMANNS Biergarten', 'Innenstadt, 10829 Berlin, Germany', '10829', 52.4811552, 13.365461),
    ('Aquino Sommergarten', 'Hannoversche Str. 5B, 10115 Berlin, Germany', '10115', 52.5271026, 13.3847688),
    ('Mauersegler Berlin', 'Bernauer Str. 63-64, 13355 Berlin, Germany', '13355', 52.5405764, 13.4032308),
    ('Biergarten am Schlachtensee', 'Fischerhüttenstraße 136, 14163 Berlin, Germany', '14163', 52.4450583, 13.2273812),
    ('Landhaus Schupke', 'Alt-Wittenau 66, 13437 Berlin, Germany', '13437', 52.5914701, 13.3266431),
    ('Bootshaus Sportdenkmal', 'Sportpromenade 5, 12527 Berlin, Germany', '12527', 52.409142, 13.6042824),
    ('Brauhaus Spandau', 'Neuendorfer Str. 1, 13585 Berlin, Germany', '13585', 52.54071829999999, 13.2066083),
    ('Biergarten Jockel', 'Ratiborstraße 14c, 10999 Berlin, Germany', '10999', 52.4919277, 13.4385616),
    ('Biergarten auf der Insel der Jugend', 'Alt Treptow 8, 12435 Berlin, Germany', '12435', 52.48684799999999, 13.481476),
    ('Eschenbräu', 'Triftstraße 67, 13353 Berlin, Germany', '13353', 52.5434732, 13.3594853),
    ('Tiergarten-Quelle', 'S-Bahnbogen, Bachstraße 482, 10555 Berlin, Germany', '10555', 52.5151878, 13.3369127),
    ('Biergarten - Freiheit', 'Freiheit 15, 12555 Berlin, Germany', '12555', 52.4476402, 13.5767695),
    ('CapRivi', 'Am Spreebord, 10589 Berlin, Germany', '10589', 52.52088999999999, 13.3072484),
    ('Teehaus im Englischen Garten Berlin', 'Altonaer Str. 2, 10557 Berlin, Germany', '10557', 52.5171545, 13.3482004),
    ('Banja Luka', 'Falckensteinstraße 1-2, 10997 Berlin, Germany', '10997', 52.5005962, 13.4440374),
    ('Südblock', 'Admiralstraße 1-2, 10999 Berlin, Germany', '10999', 52.4985656, 13.4169759),
    ('Die Laube Biergarten', 'Hohenschönhauser Str. 80, 10369 Berlin, Germany', '10369', 52.53707319999999, 13.4660209),
    ('Sommergarten am FaF', 'Am Friedrichshain, 10407 Berlin, Germany', '10407', 52.52924429999999, 13.4301484),
    ('Bierhof Rüdersdorf', 'Am Wriezener bhf, 10243 Berlin, Germany', '10243', 52.5114125, 13.4424839),
    ('Babette''s Garten', 'Am Sudhaus 3, 12053 Berlin, Germany', '12053', 52.47904, 13.431162),
    ('Zur Gerichtslaube', 'Poststraße 28, 10178 Berlin, Germany', '10178', 52.5170542, 13.4063319),
    ('Kulturhaus Insel Berlin', 'Alt Treptow 6, 12435 Berlin, Germany', '12435', 52.48678, 13.4808),
    ('Rosengarten Kulturpavillon', 'Weinbergsweg 13, 10119 Berlin, Germany', '10119', 52.5324776, 13.4034001),
    ('Bergterrasse Marienhöhe', 'Marienhöher Weg 30, 12105 Berlin, Germany', '12105', 52.45209, 13.36739),
    ('Sommergarten Jungfernheide', 'Heckerdamm 260, 13627 Berlin, Germany', '13627', 52.54374499999999, 13.290956),
    ('Emma & Paul''s Biergarten / Eiskrem Hausgemacht', 'Am Hafen Kladow, Imchenallee 42, 14089 Berlin, Germany', '14089', 52.4517974, 13.1476669),
    ('Biergarten Rudower Höhe bei Käse Paul', 'Casino "Zum Frühbeet", Wolfram Huger, Künnekeweg 20, 12355 Berlin, Germany', '12355', 52.4159503, 13.5199294),
    ('Biergarten der Tiergartenquelle', 'Bachstraße 11, 10555 Berlin, Germany', '10555', 52.5151754, 13.3369668),
    ('Zosse �?Bar / Biergarten', 'Richardstraße 37, 12043 Berlin, Germany', '12043', 52.47500489999999, 13.4437443),
    ('Kulturbiergarten Jungfernheide', 'gegenüber Heckerdamm 273, 13627, 13629 Berlin, Germany', '13627', 52.542427, 13.281615),
    ('FISHERMANS SeeGarten', 'Borsigdamm 11, 13507 Berlin, Germany', '13507', 52.5848741, 13.2758693),
    ('Biergarten am Herthasee', 'Bismarckallee 23, 14193 Berlin, Germany', '14193', 52.4885511, 13.2770456),
    ('Alte Turnhalle', 'Holteistraße 6-9, 10245 Berlin, Germany', '10245', 52.5072217, 13.4652699),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 'Schmöckwitzer Damm 1G, 12527 Berlin, Germany', '12527', 52.36916340000001, 13.6500961),
    ('South Beer Garden', 'Priesterweg 10, 12157 Berlin, Germany', '12157', 52.46083600000001, 13.356189),
    ('White Lounge Shisha', 'Goebenstraße 14, 10783 Berlin, Germany', '10783', 52.4932414, 13.3663456),
    ('11n Lounge', 'Grünberger Str. 60, 10245 Berlin, Germany', '10245', 52.5116854, 13.4565511),
    ('BER Lounge Tempelhof', 'Melli-Beese-Ring 1, 12529 Schönefeld, Germany', '12529', 52.3609693, 13.509099),
    ('DB Lounge Berlin Hbf', 'Wandelhalle Ost, Europaplatz 1/1.OG, 10557 Berlin, Germany', '10557', 52.5249082, 13.369493),
    ('PanAm Lounge', 'Budapester Str. 43, 10787 Berlin, Germany', '10787', 52.5050697, 13.3398762),
    ('BER Lounge Tegel', 'Willy-Brandt-Platz 1, 12529 Schönefeld, Germany', '12529', 52.36622, 13.505965),
    ('Floating Lounge at Shipotel', 'Mühlenstraße 73, 10243 Berlin, Germany', '10243', 52.5033019, 13.4442895)
) AS loc(name, address_line, postal_code, latitude, longitude) ON ib.name = loc.name;

-- 插入bar_themes表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'Cassiopeia Sommergarten',
        'Weihenstephaner Berlin',
        'Holzmarkt 25',
        'Bier & Garten JamesHobrecht',
        'Wannseeterrassen Berlin',
        'Biergarten Strandbar Berlista',
        'Fischerhütte am Schlachtensee',
        'Biergarten am Kleinen Tiergarten',
        'NAUMANNS Biergarten',
        'Aquino Sommergarten',
        'Mauersegler Berlin',
        'Biergarten am Schlachtensee',
        'Landhaus Schupke',
        'Bootshaus Sportdenkmal',
        'Brauhaus Spandau',
        'Biergarten Jockel',
        'Biergarten auf der Insel der Jugend',
        'Eschenbräu',
        'Tiergarten-Quelle',
        'Biergarten - Freiheit',
        'CapRivi',
        'Teehaus im Englischen Garten Berlin',
        'Banja Luka',
        'Südblock',
        'Die Laube Biergarten',
        'Sommergarten am FaF',
        'Bierhof Rüdersdorf',
        'Babette''s Garten',
        'Zur Gerichtslaube',
        'Kulturhaus Insel Berlin',
        'Rosengarten Kulturpavillon',
        'Bergterrasse Marienhöhe',
        'Sommergarten Jungfernheide',
        'Emma & Paul''s Biergarten / Eiskrem Hausgemacht',
        'Biergarten Rudower Höhe bei Käse Paul',
        'Biergarten der Tiergartenquelle',
        'Zosse �?Bar / Biergarten',
        'Kulturbiergarten Jungfernheide',
        'FISHERMANS SeeGarten',
        'Biergarten am Herthasee',
        'Alte Turnhalle',
        'Karibik Berlin Köpenick - Strandbar und Biergarten',
        'South Beer Garden',
        'White Lounge Shisha',
        '11n Lounge',
        'BER Lounge Tempelhof',
        'DB Lounge Berlin Hbf',
        'PanAm Lounge',
        'BER Lounge Tegel',
        'Floating Lounge at Shipotel'
    )
)
INSERT INTO public.bar_themes (bar_id, theme_id)
SELECT ib.id, t.id
FROM inserted_bars ib
JOIN (VALUES
    ('Cassiopeia Sommergarten', 'cocktails'),
    ('Cassiopeia Sommergarten', 'food'),
    ('Weihenstephaner Berlin', 'cocktails'),
    ('Weihenstephaner Berlin', 'food'),
    ('Holzmarkt 25', 'cocktails'),
    ('Holzmarkt 25', 'food'),
    ('Holzmarkt 25', 'electronic'),
    ('Bier & Garten JamesHobrecht', 'cocktails'),
    ('Bier & Garten JamesHobrecht', 'food'),
    ('Wannseeterrassen Berlin', 'cocktails'),
    ('Wannseeterrassen Berlin', 'food'),
    ('Wannseeterrassen Berlin', 'spirits'),
    ('Biergarten Strandbar Berlista', 'cocktails'),
    ('Biergarten Strandbar Berlista', 'food'),
    ('Fischerhütte am Schlachtensee', 'cocktails'),
    ('Fischerhütte am Schlachtensee', 'food'),
    ('Biergarten am Kleinen Tiergarten', 'cocktails'),
    ('Biergarten am Kleinen Tiergarten', 'food'),
    ('NAUMANNS Biergarten', 'cocktails'),
    ('NAUMANNS Biergarten', 'food'),
    ('Aquino Sommergarten', 'cocktails'),
    ('Aquino Sommergarten', 'food'),
    ('Mauersegler Berlin', 'cocktails'),
    ('Mauersegler Berlin', 'food'),
    ('Mauersegler Berlin', 'electronic'),
    ('Biergarten am Schlachtensee', 'cocktails'),
    ('Biergarten am Schlachtensee', 'food'),
    ('Landhaus Schupke', 'cocktails'),
    ('Landhaus Schupke', 'food'),
    ('Bootshaus Sportdenkmal', 'cocktails'),
    ('Bootshaus Sportdenkmal', 'food'),
    ('Brauhaus Spandau', 'cocktails'),
    ('Brauhaus Spandau', 'food'),
    ('Brauhaus Spandau', 'spirits'),
    ('Biergarten Jockel', 'cocktails'),
    ('Biergarten Jockel', 'food'),
    ('Biergarten auf der Insel der Jugend', 'cocktails'),
    ('Biergarten auf der Insel der Jugend', 'food'),
    ('Eschenbräu', 'cocktails'),
    ('Eschenbräu', 'food'),
    ('Tiergarten-Quelle', 'cocktails'),
    ('Tiergarten-Quelle', 'food'),
    ('Biergarten - Freiheit', 'cocktails'),
    ('Biergarten - Freiheit', 'food'),
    ('CapRivi', 'cocktails'),
    ('CapRivi', 'food'),
    ('Teehaus im Englischen Garten Berlin', 'cocktails'),
    ('Teehaus im Englischen Garten Berlin', 'food'),
    ('Banja Luka', 'cocktails'),
    ('Banja Luka', 'food'),
    ('Südblock', 'cocktails'),
    ('Südblock', 'food'),
    ('Die Laube Biergarten', 'cocktails'),
    ('Die Laube Biergarten', 'food'),
    ('Sommergarten am FaF', 'cocktails'),
    ('Sommergarten am FaF', 'food'),
    ('Bierhof Rüdersdorf', 'cocktails'),
    ('Bierhof Rüdersdorf', 'food'),
    ('Babette''s Garten', 'cocktails'),
    ('Babette''s Garten', 'food'),
    ('Zur Gerichtslaube', 'cocktails'),
    ('Zur Gerichtslaube', 'food'),
    ('Kulturhaus Insel Berlin', 'cocktails'),
    ('Kulturhaus Insel Berlin', 'food'),
    ('Rosengarten Kulturpavillon', 'cocktails'),
    ('Rosengarten Kulturpavillon', 'food'),
    ('Bergterrasse Marienhöhe', 'cocktails'),
    ('Bergterrasse Marienhöhe', 'food'),
    ('Sommergarten Jungfernheide', 'cocktails'),
    ('Sommergarten Jungfernheide', 'food'),
    ('Sommergarten Jungfernheide', 'spirits'),
    ('Emma & Paul''s Biergarten / Eiskrem Hausgemacht', 'cocktails'),
    ('Emma & Paul''s Biergarten / Eiskrem Hausgemacht', 'food'),
    ('Emma & Paul''s Biergarten / Eiskrem Hausgemacht', 'spirits'),
    ('Biergarten Rudower Höhe bei Käse Paul', 'cocktails'),
    ('Biergarten Rudower Höhe bei Käse Paul', 'food'),
    ('Biergarten der Tiergartenquelle', 'cocktails'),
    ('Biergarten der Tiergartenquelle', 'food'),
    ('Zosse �?Bar / Biergarten', 'cocktails'),
    ('Kulturbiergarten Jungfernheide', 'cocktails'),
    ('Kulturbiergarten Jungfernheide', 'food'),
    ('FISHERMANS SeeGarten', 'cocktails'),
    ('FISHERMANS SeeGarten', 'food'),
    ('Biergarten am Herthasee', 'cocktails'),
    ('Biergarten am Herthasee', 'food'),
    ('Alte Turnhalle', 'cocktails'),
    ('Alte Turnhalle', 'food'),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 'cocktails'),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 'food'),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 'electronic'),
    ('Karibik Berlin Köpenick - Strandbar und Biergarten', 'spirits'),
    ('South Beer Garden', 'cocktails'),
    ('South Beer Garden', 'food'),
    ('White Lounge Shisha', 'food'),
    ('White Lounge Shisha', 'cocktails'),
    ('11n Lounge', 'cocktails'),
    ('11n Lounge', 'electronic'),
    ('BER Lounge Tempelhof', 'cocktails'),
    ('DB Lounge Berlin Hbf', 'cocktails'),
    ('DB Lounge Berlin Hbf', 'electronic'),
    ('PanAm Lounge', 'cocktails'),
    ('BER Lounge Tegel', 'cocktails'),
    ('Floating Lounge at Shipotel', 'cocktails'),
    ('Floating Lounge at Shipotel', 'electronic')
) AS bt(bar_name, theme_name) ON ib.name = bt.bar_name
JOIN public.themes t ON t.name = bt.theme_name;

COMMIT;

-- 批次 6: 记录 251-300
