BEGIN;

-- 插入bars表数�?INSERT INTO public.bars (name, district_id, description, cash_only, card_accepted) VALUES
    ('Pluto', 1, '评分 4.6/5 (50 条评�? | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Vinoteca Berlin Weinbar Aperitivo Weinhandel', 1, '评分 4.8/5 (211 条评�? | 2 | 类型: bar, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('Le Balto', 1, '评分 4.4/5 (180 条评�? | 类型: bar, establishment, food, point_of_interest', false, false),
    ('DRUNK by nature', 1, '评分 4.5/5 (20 条评�? | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Jane & the Jam', 1, '评分 4.6/5 (85 条评�? | 类型: bar, establishment, food, grocery_or_supermarket, point_of_interest, store', false, false),
    ('der Weinlobbyist - Restaurant & Weinbar', 1, '评分 4.8/5 (306 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Vineria Carvalho', 1, '评分 4.5/5 (86 条评�? | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Zerostress Weinbar & Restaurant', 1, '评分 4.9/5 (104 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Sagrantino', 1, '评分 4.6/5 (1134 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('ORA Restaurant & Wine Bar', 1, '评分 4.2/5 (1168 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Planet Wein - Weinhandel am Gendarmenmarkt', 1, '评分 4.7/5 (370 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, store', false, false),
    ('Kurpfalz-Weinstuben', 1, '评分 4.7/5 (508 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Weinerei Forum Weinbar', 1, '评分 4.3/5 (1444 条评�? | 类型: establishment, food, liquor_store, point_of_interest, store', false, false),
    ('Bom aus Portugal - Weinbar und Restaurant', 1, '评分 4.8/5 (136 条评�? | 2 | 类型: bar, cafe, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('MORE Natural Wine', 1, '评分 4.8/5 (86 条评�? | 类型: establishment, food, liquor_store, point_of_interest, store', false, false),
    ('Tastavin', 1, '评分 4.6/5 (92 条评�? | 2 | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Freundschaft', 1, '评分 4.3/5 (432 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Weinladen Schmidt Charlottenburg', 1, '评分 4.6/5 (118 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('Lobby 030', 1, '评分 4.6/5 (24 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Bredouille Bar', 1, '评分 4.7/5 (270 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('altrovino Weinhandlung & Weinbar', 1, '评分 4.8/5 (82 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('Weinhandlung Les Climats', 1, '类型: bar, establishment, food, liquor_store, point_of_interest, store', false, false),
    ('KINK Bar & Restaurant', 1, '评分 4.7/5 (1126 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('weinverein', 1, '评分 4.5/5 (322 条评�? | 2 | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Bar Nonno', 1, '评分 4.7/5 (228 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Baden im Wein', 1, '评分 4.6/5 (238 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('La Cantine d''Augusta Käse Restaurant & Wein Bar', 1, '评分 4.7/5 (716 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('jaja', 1, '评分 4.3/5 (629 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('ILOsBAR | Cocktails �?Drinks �?Mini Club', 1, '评分 5/5 (42 条评�? | 类型: bar, establishment, food, night_club, point_of_interest, restaurant', false, false),
    ('Weinmoral Berlin', 1, '评分 5/5 (41 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, store', false, false),
    ('Dreiviertel Weine Berlin', 1, '评分 4.6/5 (61 条评�? | 类型: establishment, food, liquor_store, point_of_interest, restaurant, store', false, false),
    ('SOOT Bar', 1, '评分 4.2/5 (22 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Vinscent Weinstudio Wedding', 1, '评分 4.9/5 (70 条评�? | 类型: bar, establishment, food, liquor_store, point_of_interest, store', false, false),
    ('Prater Beer Garden', 1, '评分 4.3/5 (6149 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Schleusenkrug', 1, '评分 4.3/5 (6593 条评�? | 2 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Golgatha Biergarten', 1, '评分 4.3/5 (2195 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Café am Neuen See', 1, '评分 4.3/5 (10417 条评�? | 2 | 类型: bar, cafe, establishment, food, point_of_interest, restaurant', false, false),
    ('Birgit', 1, '评分 4.6/5 (3539 条评�? | 2 | 类型: bar, establishment, food, night_club, point_of_interest, restaurant', false, false),
    ('BRLO Brwhouse', 1, '评分 4.5/5 (3856 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Republic Berlin', 1, '评分 4.4/5 (996 条评�? | 2 | 类型: bar, establishment, food, meal_takeaway, point_of_interest, restaurant', false, false),
    ('Loretta am Wannsee', 1, '评分 4.4/5 (3073 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Zollpackhof', 1, '评分 4.3/5 (10028 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Zenner Biergarten und Weingarten', 1, '评分 4.4/5 (3249 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Neulich Biergarten am THF-Tower', 1, '评分 4.7/5 (180 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Augustiner auf Bötzow / Wirtshaus und Biergarten', 1, '评分 4/5 (639 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Baergarten', 1, '评分 4.2/5 (223 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('ŒLGARTEN - Beers & Bites', 1, '评分 4.5/5 (88 条评�? | 类型: bar, establishment, food, meal_takeaway, point_of_interest, restaurant', false, false),
    ('Alter Krug Dahlem', 1, '评分 4.2/5 (2494 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('TEMPEL GARTEN', 1, '评分 4.3/5 (260 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('James June Event GmbH', 1, '评分 4.6/5 (1454 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false);

-- 插入bar_locations表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'Pluto',
        'Vinoteca Berlin Weinbar Aperitivo Weinhandel',
        'Le Balto',
        'DRUNK by nature',
        'Jane & the Jam',
        'der Weinlobbyist - Restaurant & Weinbar',
        'Vineria Carvalho',
        'Zerostress Weinbar & Restaurant',
        'Sagrantino',
        'ORA Restaurant & Wine Bar',
        'Planet Wein - Weinhandel am Gendarmenmarkt',
        'Kurpfalz-Weinstuben',
        'Weinerei Forum Weinbar',
        'Bom aus Portugal - Weinbar und Restaurant',
        'MORE Natural Wine',
        'Tastavin',
        'Freundschaft',
        'Weinladen Schmidt Charlottenburg',
        'Lobby 030',
        'Bredouille Bar',
        'altrovino Weinhandlung & Weinbar',
        'Weinhandlung Les Climats',
        'KINK Bar & Restaurant',
        'weinverein',
        'Bar Nonno',
        'Baden im Wein',
        'La Cantine d''Augusta Käse Restaurant & Wein Bar',
        'jaja',
        'ILOsBAR | Cocktails �?Drinks �?Mini Club',
        'Weinmoral Berlin',
        'Dreiviertel Weine Berlin',
        'SOOT Bar',
        'Vinscent Weinstudio Wedding',
        'Prater Beer Garden',
        'Schleusenkrug',
        'Golgatha Biergarten',
        'Café am Neuen See',
        'Birgit',
        'BRLO Brwhouse',
        'Republic Berlin',
        'Loretta am Wannsee',
        'Zollpackhof',
        'Zenner Biergarten und Weingarten',
        'Neulich Biergarten am THF-Tower',
        'Augustiner auf Bötzow / Wirtshaus und Biergarten',
        'Baergarten',
        'ŒLGARTEN - Beers & Bites',
        'Alter Krug Dahlem',
        'TEMPEL GARTEN',
        'James June Event GmbH'
    )
)
INSERT INTO public.bar_locations (bar_id, address_line, postal_code, latitude, longitude)
SELECT ib.id, loc.address_line, loc.postal_code, loc.latitude, loc.longitude
FROM inserted_bars ib
JOIN (VALUES
    ('Pluto', 'Kastanienallee 27, 10435 Berlin, Germany', '10435', 52.5373612, 13.4081675),
    ('Vinoteca Berlin Weinbar Aperitivo Weinhandel', 'Windscheidstraße 22, 10627 Berlin, Germany', '10627', 52.5055187, 13.2999347),
    ('Le Balto', 'Hobrechtstraße 28, 12047 Berlin, Germany', '12047', 52.4909709, 13.4262801),
    ('DRUNK by nature', 'Eisenbahnstraße 42, 10997 Berlin, Germany', '10997', 52.5021335, 13.4316207),
    ('Jane & the Jam', 'Brunnenstraße 27, 10119 Berlin, Germany', '10119', 52.5342087, 13.3987134),
    ('der Weinlobbyist - Restaurant & Weinbar', 'Kolonnenstraße 62, 10827 Berlin, Germany', '10827', 52.48666, 13.35925),
    ('Vineria Carvalho', 'Reichenberger Str. 54, 10999 Berlin, Germany', '10999', 52.4961341, 13.4277516),
    ('Zerostress Weinbar & Restaurant', 'Friesenstraße 21, 10965 Berlin, Germany', '10965', 52.4877374, 13.3947706),
    ('Sagrantino', 'Behrenstraße 47, 10117 Berlin, Germany', '10117', 52.5158619, 13.3902558),
    ('ORA Restaurant & Wine Bar', 'Oranienpl. 14, 10999 Berlin, Germany', '10999', 52.5013623, 13.4159217),
    ('Planet Wein - Weinhandel am Gendarmenmarkt', 'Mohrenstraße, Eingang, Charlottenstraße 30, 10117 Berlin, Germany', '10117', 52.5118276, 13.3917541),
    ('Kurpfalz-Weinstuben', 'Wilmersdorfer Str. 93, 10629 Berlin, Germany', '10629', 52.5009559, 13.3076999),
    ('Weinerei Forum Weinbar', 'Fehrbelliner Str. 57, 10119 Berlin, Germany', '10119', 52.5336537, 13.4025479),
    ('Bom aus Portugal - Weinbar und Restaurant', 'Friesenstraße 7, 10965 Berlin, Germany', '10965', 52.4877388, 13.3942132),
    ('MORE Natural Wine', 'Flughafenstraße 22, 12053 Berlin, Germany', '12053', 52.4816076, 13.4303279),
    ('Tastavin', 'Arminiusstraße 2-4, 10551 Berlin, Germany', '10551', 52.5279846, 13.3387897),
    ('Freundschaft', 'Mittelstraße 1, 10117 Berlin, Germany', '10117', 52.5182501, 13.390308),
    ('Weinladen Schmidt Charlottenburg', 'Pestalozzistraße 85, 10625 Berlin, Germany', '10625', 52.5077028, 13.3098352),
    ('Lobby 030', 'Richardstraße 76, 12043 Berlin, Germany', '12043', 52.4747357, 13.4448681),
    ('Bredouille Bar', 'S-Bahnbogen 199, Georgenstraße, 10117 Berlin, Germany', '10117', 52.5199995, 13.3898338),
    ('altrovino Weinhandlung & Weinbar', 'Grimmstraße 17, 10967 Berlin, Germany', '10967', 52.4920622, 13.4138561),
    ('Weinhandlung Les Climats', 'Pohlstraße 75, 10785 Berlin, Germany', '10785', 52.5010244, 13.3623347),
    ('KINK Bar & Restaurant', 'Schönhauser Allee 176, 10119 Berlin, Germany', '10119', 52.5319735, 13.4115959),
    ('weinverein', 'Leuthener Str. 5, 10829 Berlin, Germany', '10829', 52.481258, 13.3611175),
    ('Bar Nonno', 'Akazienstraße 7A, 10823 Berlin, Germany', '10823', 52.4878533, 13.3545943),
    ('Baden im Wein', 'Schönhauser Allee 155, 10435 Berlin, Germany', '10435', 52.5375936, 13.4117808),
    ('La Cantine d''Augusta Käse Restaurant & Wein Bar', 'Langenscheidtstraße 6A, 10827 Berlin, Germany', '10827', 52.4891205, 13.3621136),
    ('jaja', 'Weichselstraße 7, 12043 Berlin, Germany', '12043', 52.48421579999999, 13.4331469),
    ('ILOsBAR | Cocktails �?Drinks �?Mini Club', 'Motzstraße 30, 10777 Berlin, Germany', '10777', 52.4977015, 13.3474396),
    ('Weinmoral Berlin', 'Mommsenstraße 30, 10629 Berlin, Germany', '10629', 52.5037554, 13.3070484),
    ('Dreiviertel Weine Berlin', 'Oderberger Str. 39, 10435 Berlin, Germany', '10435', 52.5396209, 13.4062847),
    ('SOOT Bar', 'Marlene-Dietrich-Platz 3, 10785 Berlin, Germany', '10785', 52.5077089, 13.3731988),
    ('Vinscent Weinstudio Wedding', 'Transvaalstraße 43, 13351 Berlin, Germany', '13351', 52.5534707, 13.3442412),
    ('Prater Beer Garden', 'Kastanienallee 7-9, 10435 Berlin, Germany', '10435', 52.540099, 13.4097855),
    ('Schleusenkrug', 'Müller-Breslau-Straße 14b, 10623 Berlin, Germany', '10623', 52.5112761, 13.3358521),
    ('Golgatha Biergarten', 'Katzbachstraße &, Monumentenstraße, 10965 Berlin, Germany', '10965', 52.4867247, 13.3786009),
    ('Café am Neuen See', 'Lichtensteinallee 2, 10787 Berlin, Germany', '10787', 52.5103772, 13.3444862),
    ('Birgit', 'Schleusenufer 3, 10997 Berlin, Germany', '10997', 52.49780519999999, 13.4499834),
    ('BRLO Brwhouse', 'Schöneberger Str. 16, 10963 Berlin, Germany', '10963', 52.5001966, 13.3737),
    ('Republic Berlin', 'Köpenicker Str. 74, 10179 Berlin, Germany', '10179', 52.5109542, 13.417325),
    ('Loretta am Wannsee', 'Kronprinzessinnenweg 260, 14109 Berlin, Germany', '14109', 52.4199832, 13.1759261),
    ('Zollpackhof', 'Elisabeth-Abegg-Straße 1, 10557 Berlin, Germany', '10557', 52.5213107, 13.3668981),
    ('Zenner Biergarten und Weingarten', 'Alt Treptow 15, 12435 Berlin, Germany', '12435', 52.487488, 13.4778311),
    ('Neulich Biergarten am THF-Tower', 'Tempelhofer Damm 45, 12101 Berlin, Germany', '12101', 52.4769808, 13.3873816),
    ('Augustiner auf Bötzow / Wirtshaus und Biergarten', 'Prenzlauer Allee 242, 10405 Berlin, Germany', '10405', 52.5294246, 13.4168594),
    ('Baergarten', 'Schnellerstraße 137, 12439 Berlin, Germany', '12439', 52.4602432, 13.5056877),
    ('ŒLGARTEN - Beers & Bites', 'Schleusenufer 1, 10997 Berlin, Germany', '10997', 52.4973304, 13.4494969),
    ('Alter Krug Dahlem', 'Königin-Luise-Straße 52, 14195 Berlin, Germany', '14195', 52.4578876, 13.2882223),
    ('TEMPEL GARTEN', 'Columbiadamm, Tempelhofer Feld, Gebäude 462, 12049 Berlin, Germany', '12049', 52.4793122, 13.4093339),
    ('James June Event GmbH', 'Karl-Marx-Allee 93, 10243 Berlin, Germany', '10243', 52.5178184, 13.4414425)
) AS loc(name, address_line, postal_code, latitude, longitude) ON ib.name = loc.name;

-- 插入bar_themes表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'Pluto',
        'Vinoteca Berlin Weinbar Aperitivo Weinhandel',
        'Le Balto',
        'DRUNK by nature',
        'Jane & the Jam',
        'der Weinlobbyist - Restaurant & Weinbar',
        'Vineria Carvalho',
        'Zerostress Weinbar & Restaurant',
        'Sagrantino',
        'ORA Restaurant & Wine Bar',
        'Planet Wein - Weinhandel am Gendarmenmarkt',
        'Kurpfalz-Weinstuben',
        'Weinerei Forum Weinbar',
        'Bom aus Portugal - Weinbar und Restaurant',
        'MORE Natural Wine',
        'Tastavin',
        'Freundschaft',
        'Weinladen Schmidt Charlottenburg',
        'Lobby 030',
        'Bredouille Bar',
        'altrovino Weinhandlung & Weinbar',
        'Weinhandlung Les Climats',
        'KINK Bar & Restaurant',
        'weinverein',
        'Bar Nonno',
        'Baden im Wein',
        'La Cantine d''Augusta Käse Restaurant & Wein Bar',
        'jaja',
        'ILOsBAR | Cocktails �?Drinks �?Mini Club',
        'Weinmoral Berlin',
        'Dreiviertel Weine Berlin',
        'SOOT Bar',
        'Vinscent Weinstudio Wedding',
        'Prater Beer Garden',
        'Schleusenkrug',
        'Golgatha Biergarten',
        'Café am Neuen See',
        'Birgit',
        'BRLO Brwhouse',
        'Republic Berlin',
        'Loretta am Wannsee',
        'Zollpackhof',
        'Zenner Biergarten und Weingarten',
        'Neulich Biergarten am THF-Tower',
        'Augustiner auf Bötzow / Wirtshaus und Biergarten',
        'Baergarten',
        'ŒLGARTEN - Beers & Bites',
        'Alter Krug Dahlem',
        'TEMPEL GARTEN',
        'James June Event GmbH'
    )
)
INSERT INTO public.bar_themes (bar_id, theme_id)
SELECT ib.id, t.id
FROM inserted_bars ib
JOIN (VALUES
    ('Pluto', 'cocktails'),
    ('Pluto', 'food'),
    ('Vinoteca Berlin Weinbar Aperitivo Weinhandel', 'cocktails'),
    ('Vinoteca Berlin Weinbar Aperitivo Weinhandel', 'food'),
    ('Vinoteca Berlin Weinbar Aperitivo Weinhandel', 'spirits'),
    ('Le Balto', 'cocktails'),
    ('Le Balto', 'food'),
    ('DRUNK by nature', 'cocktails'),
    ('DRUNK by nature', 'food'),
    ('Jane & the Jam', 'cocktails'),
    ('Jane & the Jam', 'food'),
    ('Jane & the Jam', 'spirits'),
    ('der Weinlobbyist - Restaurant & Weinbar', 'cocktails'),
    ('der Weinlobbyist - Restaurant & Weinbar', 'food'),
    ('Vineria Carvalho', 'cocktails'),
    ('Vineria Carvalho', 'food'),
    ('Zerostress Weinbar & Restaurant', 'cocktails'),
    ('Zerostress Weinbar & Restaurant', 'food'),
    ('Sagrantino', 'cocktails'),
    ('Sagrantino', 'food'),
    ('ORA Restaurant & Wine Bar', 'cocktails'),
    ('ORA Restaurant & Wine Bar', 'food'),
    ('Planet Wein - Weinhandel am Gendarmenmarkt', 'cocktails'),
    ('Planet Wein - Weinhandel am Gendarmenmarkt', 'food'),
    ('Planet Wein - Weinhandel am Gendarmenmarkt', 'spirits'),
    ('Kurpfalz-Weinstuben', 'cocktails'),
    ('Kurpfalz-Weinstuben', 'food'),
    ('Weinerei Forum Weinbar', 'cocktails'),
    ('Weinerei Forum Weinbar', 'food'),
    ('Weinerei Forum Weinbar', 'spirits'),
    ('Bom aus Portugal - Weinbar und Restaurant', 'cocktails'),
    ('Bom aus Portugal - Weinbar und Restaurant', 'food'),
    ('Bom aus Portugal - Weinbar und Restaurant', 'spirits'),
    ('MORE Natural Wine', 'cocktails'),
    ('MORE Natural Wine', 'food'),
    ('MORE Natural Wine', 'spirits'),
    ('Tastavin', 'cocktails'),
    ('Tastavin', 'food'),
    ('Freundschaft', 'cocktails'),
    ('Weinladen Schmidt Charlottenburg', 'cocktails'),
    ('Weinladen Schmidt Charlottenburg', 'food'),
    ('Weinladen Schmidt Charlottenburg', 'spirits'),
    ('Lobby 030', 'cocktails'),
    ('Lobby 030', 'food'),
    ('Bredouille Bar', 'cocktails'),
    ('Bredouille Bar', 'food'),
    ('altrovino Weinhandlung & Weinbar', 'cocktails'),
    ('altrovino Weinhandlung & Weinbar', 'food'),
    ('altrovino Weinhandlung & Weinbar', 'spirits'),
    ('Weinhandlung Les Climats', 'cocktails'),
    ('Weinhandlung Les Climats', 'food'),
    ('Weinhandlung Les Climats', 'spirits'),
    ('KINK Bar & Restaurant', 'cocktails'),
    ('KINK Bar & Restaurant', 'food'),
    ('weinverein', 'cocktails'),
    ('weinverein', 'food'),
    ('Bar Nonno', 'cocktails'),
    ('Baden im Wein', 'cocktails'),
    ('Baden im Wein', 'food'),
    ('La Cantine d''Augusta Käse Restaurant & Wein Bar', 'cocktails'),
    ('La Cantine d''Augusta Käse Restaurant & Wein Bar', 'food'),
    ('jaja', 'cocktails'),
    ('jaja', 'food'),
    ('ILOsBAR | Cocktails �?Drinks �?Mini Club', 'cocktails'),
    ('ILOsBAR | Cocktails �?Drinks �?Mini Club', 'food'),
    ('ILOsBAR | Cocktails �?Drinks �?Mini Club', 'electronic'),
    ('Weinmoral Berlin', 'cocktails'),
    ('Weinmoral Berlin', 'food'),
    ('Weinmoral Berlin', 'spirits'),
    ('Dreiviertel Weine Berlin', 'cocktails'),
    ('Dreiviertel Weine Berlin', 'food'),
    ('Dreiviertel Weine Berlin', 'spirits'),
    ('SOOT Bar', 'cocktails'),
    ('SOOT Bar', 'food'),
    ('Vinscent Weinstudio Wedding', 'cocktails'),
    ('Vinscent Weinstudio Wedding', 'food'),
    ('Vinscent Weinstudio Wedding', 'spirits'),
    ('Prater Beer Garden', 'cocktails'),
    ('Prater Beer Garden', 'food'),
    ('Schleusenkrug', 'cocktails'),
    ('Schleusenkrug', 'food'),
    ('Schleusenkrug', 'spirits'),
    ('Golgatha Biergarten', 'cocktails'),
    ('Golgatha Biergarten', 'food'),
    ('Café am Neuen See', 'cocktails'),
    ('Café am Neuen See', 'food'),
    ('Birgit', 'cocktails'),
    ('Birgit', 'food'),
    ('Birgit', 'electronic'),
    ('BRLO Brwhouse', 'cocktails'),
    ('BRLO Brwhouse', 'food'),
    ('Republic Berlin', 'cocktails'),
    ('Republic Berlin', 'food'),
    ('Loretta am Wannsee', 'cocktails'),
    ('Loretta am Wannsee', 'food'),
    ('Zollpackhof', 'cocktails'),
    ('Zollpackhof', 'food'),
    ('Zenner Biergarten und Weingarten', 'cocktails'),
    ('Zenner Biergarten und Weingarten', 'food'),
    ('Neulich Biergarten am THF-Tower', 'cocktails'),
    ('Neulich Biergarten am THF-Tower', 'food'),
    ('Augustiner auf Bötzow / Wirtshaus und Biergarten', 'cocktails'),
    ('Augustiner auf Bötzow / Wirtshaus und Biergarten', 'food'),
    ('Baergarten', 'cocktails'),
    ('Baergarten', 'food'),
    ('ŒLGARTEN - Beers & Bites', 'cocktails'),
    ('ŒLGARTEN - Beers & Bites', 'food'),
    ('Alter Krug Dahlem', 'cocktails'),
    ('Alter Krug Dahlem', 'food'),
    ('TEMPEL GARTEN', 'cocktails'),
    ('TEMPEL GARTEN', 'food'),
    ('James June Event GmbH', 'cocktails'),
    ('James June Event GmbH', 'food')
) AS bt(bar_name, theme_name) ON ib.name = bt.bar_name
JOIN public.themes t ON t.name = bt.theme_name;

COMMIT;

-- 批次 5: 记录 201-250
