BEGIN;

-- 插入bars表数�?INSERT INTO public.bars (name, district_id, description, cash_only, card_accepted) VALUES
    ('One Lounge', 1, '评分 4.9/5 (15 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Lufthansa Business Lounge', 1, '评分 3.8/5 (1568 条评�? | 1 | 类型: establishment, point_of_interest', false, false),
    ('Kiss Lounge', 1, '评分 3.8/5 (120 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('DB Premium Lounge Berlin Hbf', 1, '评分 4.3/5 (221 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Shadow Lounge', 1, '评分 4.7/5 (202 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Balcone Lounge', 1, '评分 4.8/5 (457 条评�? | 2 | 类型: bar, establishment, food, night_club, point_of_interest, restaurant', false, false),
    ('The Vibe lounge women''s cafe', 1, '评分 4.9/5 (399 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Noor Lounge - Shisha Bar Berlin', 1, '评分 4.9/5 (1132 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Mirror Lounge', 1, '评分 4.7/5 (618 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Society Lounge', 1, '评分 4.5/5 (377 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Luna Lounge Hookah&Restaurant', 1, '评分 4.9/5 (152 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Lobby Lounge & Bar Hotel Adlon', 1, '评分 4.6/5 (3842 条评�? | 4 | 类型: bar, cafe, establishment, food, night_club, point_of_interest', false, false),
    ('Zoé Lounge Berlin Hookah & Restaurant', 1, '评分 4.4/5 (389 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Palm Lounge', 1, '评分 4.4/5 (31 条评�? | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Diamond Bar - Café - Lounge', 1, '评分 4.8/5 (24 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Bar Solut', 1, '评分 4.3/5 (339 条评�? | 1 | 类型: bar, cafe, establishment, food, night_club, point_of_interest', false, false),
    ('Adara Lounge', 1, '评分 4.6/5 (1355 条评�? | 类型: bar, cafe, establishment, food, night_club, point_of_interest', false, false),
    ('Marrakesch Lounge & Bar nähe Alexanderplatz', 1, '评分 4.7/5 (1392 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('King''s Lounge', 1, '评分 4.8/5 (157 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Neelou Lounge', 1, '评分 4.5/5 (264 条评�? | 2 | 类型: cafe, establishment, food, point_of_interest', false, false),
    ('VIP Lounge Zeitgeist Right of way', 1, '评分 4.6/5 (123 条评�? | 4 | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('Vikings Lounge', 1, '评分 4.6/5 (301 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Karizma Lounge Berlin', 1, '评分 4.8/5 (226 条评�? | 类型: establishment, point_of_interest', false, false),
    ('GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte', 1, '评分 4.3/5 (4499 条评�? | 2 | 类型: bar, establishment, food, meal_takeaway, point_of_interest, restaurant', false, false),
    ('The Lounge', 1, '评分 4.3/5 (28 条评�? | 类型: bar, establishment, point_of_interest', false, false),
    ('Chill Out Bar', 1, '评分 4.5/5 (234 条评�? | 1 | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('Coco Lounge', 1, '评分 4.2/5 (281 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Loft14', 1, '评分 4.2/5 (823 条评�? | 3 | 类型: bar, establishment, point_of_interest', false, false),
    ('The Leaf | Shisha Lounge Berlin', 1, '评分 4.9/5 (288 条评�? | 类型: bar, cafe, establishment, food, point_of_interest, restaurant, store', false, false),
    ('Hürrem Sultan Shisha & Cigar Bars', 1, '评分 4.8/5 (1387 条评�? | 2 | 类型: bar, cafe, establishment, food, night_club, point_of_interest, restaurant, store', false, false),
    ('Erks Lounge', 1, '评分 4.2/5 (104 条评�? | 2 | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('Bonjour Berlin Lounge', 1, '评分 3.9/5 (30 条评�? | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('Wodessa Lounge', 1, '评分 4.6/5 (112 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Maza Lounge', 1, '评分 4.6/5 (374 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Olla Berlin - Lounge and Grill', 1, '评分 4/5 (1155 条评�? | 2 | 类型: bar, establishment, food, point_of_interest, restaurant', false, false),
    ('Diamond Lounge', 1, '评分 4.3/5 (901 条评�? | 类型: bar, cafe, establishment, food, point_of_interest', false, false),
    ('Marina Lounge', 1, '评分 5/5 (23 条评�? | 类型: bar, cafe, establishment, food, night_club, point_of_interest, restaurant', false, false),
    ('100 Gramm Bar & Lounge', 1, '评分 4.8/5 (4085 条评�? | 2 | 类型: bar, establishment, food, point_of_interest', false, false),
    ('Saphire Lounge', 1, '评分 4.6/5 (19 条评�? | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('BDSM Lounge Berlin', 1, '评分 4.4/5 (101 条评�? | 类型: bar, establishment, lodging, night_club, point_of_interest', false, false),
    ('Lale Cafe - Bar - Lounge', 1, '评分 4.1/5 (237 条评�? | 2 | 类型: cafe, establishment, food, point_of_interest', false, false),
    ('Zaher''s Lounge - Café - Bar', 1, '评分 4.6/5 (901 条评�? | 2 | 类型: bar, establishment, point_of_interest', false, false),
    ('Relax Cafe-Bar-Lounge', 1, '评分 4.5/5 (35 条评�? | 类型: bar, cafe, establishment, food, point_of_interest, store', false, false),
    ('Captain Shisha Lounge', 1, '评分 4.6/5 (66 条评�? | 类型: establishment, point_of_interest', false, false),
    ('Shisha-Bar Portakal', 1, '评分 4.9/5 (130 条评�? | 类型: bar, establishment, night_club, point_of_interest', false, false),
    ('KUMO Berlin Shisha Lounge', 1, '评分 4.2/5 (193 条评�? | 类型: bar, cafe, establishment, food, night_club, point_of_interest', false, false),
    ('Pavement Luxury Lounge', 1, '评分 4/5 (20 条评�? | 类型: bar, cafe, establishment, food, night_club, point_of_interest', false, false),
    ('Narquila Bar & Shisha Lounge', 1, '评分 4.7/5 (921 条评�? | 类型: establishment, point_of_interest', false, false),
    ('111 Shisha Lounge', 1, '评分 4.4/5 (232 条评�? | 类型: establishment, point_of_interest', false, false),
    ('The Sterling Tavern', 1, '评分 4.5/5 (1080 条评�? | 2 | 类型: establishment, food, point_of_interest, restaurant', false, false);

-- 插入bar_locations表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'One Lounge',
        'Lufthansa Business Lounge',
        'Kiss Lounge',
        'DB Premium Lounge Berlin Hbf',
        'Shadow Lounge',
        'Balcone Lounge',
        'The Vibe lounge women''s cafe',
        'Noor Lounge - Shisha Bar Berlin',
        'Mirror Lounge',
        'Society Lounge',
        'Luna Lounge Hookah&Restaurant',
        'Lobby Lounge & Bar Hotel Adlon',
        'Zoé Lounge Berlin Hookah & Restaurant',
        'Palm Lounge',
        'Diamond Bar - Café - Lounge',
        'Bar Solut',
        'Adara Lounge',
        'Marrakesch Lounge & Bar nähe Alexanderplatz',
        'King''s Lounge',
        'Neelou Lounge',
        'VIP Lounge Zeitgeist Right of way',
        'Vikings Lounge',
        'Karizma Lounge Berlin',
        'GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte',
        'The Lounge',
        'Chill Out Bar',
        'Coco Lounge',
        'Loft14',
        'The Leaf | Shisha Lounge Berlin',
        'Hürrem Sultan Shisha & Cigar Bars',
        'Erks Lounge',
        'Bonjour Berlin Lounge',
        'Wodessa Lounge',
        'Maza Lounge',
        'Olla Berlin - Lounge and Grill',
        'Diamond Lounge',
        'Marina Lounge',
        '100 Gramm Bar & Lounge',
        'Saphire Lounge',
        'BDSM Lounge Berlin',
        'Lale Cafe - Bar - Lounge',
        'Zaher''s Lounge - Café - Bar',
        'Relax Cafe-Bar-Lounge',
        'Captain Shisha Lounge',
        'Shisha-Bar Portakal',
        'KUMO Berlin Shisha Lounge',
        'Pavement Luxury Lounge',
        'Narquila Bar & Shisha Lounge',
        '111 Shisha Lounge',
        'The Sterling Tavern'
    )
)
INSERT INTO public.bar_locations (bar_id, address_line, postal_code, latitude, longitude)
SELECT ib.id, loc.address_line, loc.postal_code, loc.latitude, loc.longitude
FROM inserted_bars ib
JOIN (VALUES
    ('One Lounge', 'Leipziger Pl. 12-13, 10117 Berlin, Germany', '10117', 52.5100154, 13.380677),
    ('Lufthansa Business Lounge', 'Willy-Brandt-Platz 1 Terminal 1, Schengen Departures, Level E2, Main Pier North Opposite, Gate B20, 12529 Schönefeld, Germany', '12529', 52.3643291, 13.5109891),
    ('Kiss Lounge', 'Wustrower Str. 12, 13051 Berlin, Germany', '13051', 52.5647909, 13.5045905),
    ('DB Premium Lounge Berlin Hbf', 'Wandelhalle Ost, Washingtonpl. 2/1.OG, 10557 Berlin, Germany', '10557', 52.5244904, 13.3704995),
    ('Shadow Lounge', 'Emser Str. 6, 10719 Berlin, Germany', '10719', 52.4936362, 13.319844),
    ('Balcone Lounge', 'Hasenheide 47, 10967 Berlin, Germany', '10967', 52.488798, 13.4118267),
    ('The Vibe lounge women''s cafe', 'Goebenstraße 10, 10783 Berlin, Germany', '10783', 52.4935181, 13.3645687),
    ('Noor Lounge - Shisha Bar Berlin', 'Knaackstraße 98, 10435 Berlin, Germany', '10435', 52.5402432, 13.4145787),
    ('Mirror Lounge', 'Skalitzer Str. 54, 10997 Berlin, Germany', '10997', 52.4995466, 13.434765),
    ('Society Lounge', 'Schwedenstraße 2, 13357 Berlin, Germany', '13357', 52.5548295, 13.3763602),
    ('Luna Lounge Hookah&Restaurant', 'Kommandantenstraße 34, 10969 Berlin, Germany', '10969', 52.5057803, 13.4063314),
    ('Lobby Lounge & Bar Hotel Adlon', 'Unter den Linden 77, 10117 Berlin, Germany', '10117', 52.5160257, 13.3803793),
    ('Zoé Lounge Berlin Hookah & Restaurant', 'Dudenstraße 72, 10965 Berlin, Germany', '10965', 52.4853117, 13.3752784),
    ('Palm Lounge', 'Gradestraße, 12347 Berlin, Germany', '12347', 52.4527657, 13.4382921),
    ('Diamond Bar - Café - Lounge', 'Residenzstraße 128, 13409 Berlin, Germany', '13409', 52.5685351, 13.3621685),
    ('Bar Solut', 'Hochstädter Str. 11, 13347 Berlin, Germany', '13347', 52.5503054, 13.3636192),
    ('Adara Lounge', 'Boxhagener Str. 75, 10245 Berlin, Germany', '10245', 52.5072278, 13.4684685),
    ('Marrakesch Lounge & Bar nähe Alexanderplatz', 'Schönhauser Allee 5, 10119 Berlin, Germany', '10119', 52.5295225, 13.4103532),
    ('King''s Lounge', 'Wilhelmstraße 163, 13595 Berlin, Germany', '13595', 52.5282805, 13.1959098),
    ('Neelou Lounge', 'Karl-Heinrich-Ulrichs-Straße 8, 10787 Berlin, Germany', '10787', 52.5011583, 13.3540298),
    ('VIP Lounge Zeitgeist Right of way', 'Melli-Beese-Ring 1, 12529 Schönefeld, Germany', '12529', 52.3613716, 13.5100747),
    ('Vikings Lounge', 'Kurfürstendamm 132A, 10711 Berlin, Germany', '10711', 52.4971372, 13.2930848),
    ('Karizma Lounge Berlin', 'Kaiser-Wilhelm-Straße 32, 12247 Berlin, Germany', '12247', 52.4319, 13.33762),
    ('GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte', 'Oranienburger Str. 33, 10117 Berlin, Germany', '10117', 52.5250481, 13.3931836),
    ('The Lounge', 'Potsdamer Platz 3, 10785 Berlin, Germany', '10785', 52.5101657, 13.3753988),
    ('Chill Out Bar', 'General-Barby-Straße 25, 13403 Berlin, Germany', '13403', 52.5688707, 13.3169938),
    ('Coco Lounge', 'Grolmanstraße 56, 10623 Berlin, Germany', '10623', 52.5081013, 13.3208625),
    ('Loft14', 'Landsberger Allee 106, 10369 Berlin, Germany', '10369', 52.5284184, 13.456966),
    ('The Leaf | Shisha Lounge Berlin', 'Residenzstraße 109, 13409 Berlin, Germany', '13409', 52.5641139, 13.3645064),
    ('Hürrem Sultan Shisha & Cigar Bars', 'Oranienstraße 52-53, 10969 Berlin, Germany', '10969', 52.50329, 13.41262),
    ('Erks Lounge', 'Fritz-Reuter-Straße 9, 10827 Berlin, Germany', '10827', 52.48046220000001, 13.348433),
    ('Bonjour Berlin Lounge', 'Nassauische Str. 36A, 10717 Berlin, Germany', '10717', 52.4869047, 13.3263637),
    ('Wodessa Lounge', 'Kaiserdamm 110, 14057 Berlin, Germany', '14057', 52.5104356, 13.292586),
    ('Maza Lounge', 'Karl-Marx-Allee 121, 10243 Berlin, Germany', '10243', 52.5169925, 13.4474868),
    ('Olla Berlin - Lounge and Grill', 'James Simon Park, Stadtbahnbogen 154-155, 10178 Berlin, Germany', '10178', 52.5222334, 13.3992169),
    ('Diamond Lounge', 'Tempelhofer Damm 224, 12099 Berlin, Germany', '12099', 52.4559712, 13.3835212),
    ('Marina Lounge', 'Kladower Damm 45, 14089 Berlin, Germany', '14089', 52.4795775, 13.1798252),
    ('100 Gramm Bar & Lounge', 'Weinbergsweg 25, 10119 Berlin, Germany', '10119', 52.5306534, 13.401757),
    ('Saphire Lounge', 'Pankower Allee 94, 13409 Berlin, Germany', '13409', 52.5645301, 13.3777997),
    ('BDSM Lounge Berlin', 'Kirchhofstraße 44, 12055 Berlin, Germany', '12055', 52.47283299999999, 13.4433093),
    ('Lale Cafe - Bar - Lounge', 'Müllerstraße 121, 13349 Berlin, Germany', '13349', 52.5540235, 13.345182),
    ('Zaher''s Lounge - Café - Bar', 'Nostitzstraße 38, 10961 Berlin, Germany', '10961', 52.4900838, 13.3905),
    ('Relax Cafe-Bar-Lounge', 'Saalestraße 30, 12055 Berlin, Germany', '12055', 52.47121010000001, 13.4523016),
    ('Captain Shisha Lounge', 'Dudenstraße 24, 10965 Berlin, Germany', '10965', 52.4851928, 13.3818812),
    ('Shisha-Bar Portakal', 'Otto-Suhr-Allee 108A, 10585 Berlin, Germany', '10585', 52.5177956, 13.3068009),
    ('KUMO Berlin Shisha Lounge', 'Wilmersdorfer Str. 152a, 10585 Berlin, Germany', '10585', 52.5146686, 13.3049948),
    ('Pavement Luxury Lounge', 'Uhlandstraße 161, 10719 Berlin, Germany', '10719', 52.4992473, 13.3249694),
    ('Narquila Bar & Shisha Lounge', 'Danziger Str. 18, 10435 Berlin, Germany', '10435', 52.54024709999999, 13.4155929),
    ('111 Shisha Lounge', 'Bayreuther Str. 3, 10787 Berlin, Germany', '10787', 52.5041257, 13.3441018),
    ('The Sterling Tavern', '119 N Main St, Berlin, MD 21811, USA', '21811', 38.3262428, -75.219608)
) AS loc(name, address_line, postal_code, latitude, longitude) ON ib.name = loc.name;

-- 插入bar_themes表数�?WITH inserted_bars AS (
    SELECT id, name FROM public.bars WHERE name IN (
        'One Lounge',
        'Lufthansa Business Lounge',
        'Kiss Lounge',
        'DB Premium Lounge Berlin Hbf',
        'Shadow Lounge',
        'Balcone Lounge',
        'The Vibe lounge women''s cafe',
        'Noor Lounge - Shisha Bar Berlin',
        'Mirror Lounge',
        'Society Lounge',
        'Luna Lounge Hookah&Restaurant',
        'Lobby Lounge & Bar Hotel Adlon',
        'Zoé Lounge Berlin Hookah & Restaurant',
        'Palm Lounge',
        'Diamond Bar - Café - Lounge',
        'Bar Solut',
        'Adara Lounge',
        'Marrakesch Lounge & Bar nähe Alexanderplatz',
        'King''s Lounge',
        'Neelou Lounge',
        'VIP Lounge Zeitgeist Right of way',
        'Vikings Lounge',
        'Karizma Lounge Berlin',
        'GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte',
        'The Lounge',
        'Chill Out Bar',
        'Coco Lounge',
        'Loft14',
        'The Leaf | Shisha Lounge Berlin',
        'Hürrem Sultan Shisha & Cigar Bars',
        'Erks Lounge',
        'Bonjour Berlin Lounge',
        'Wodessa Lounge',
        'Maza Lounge',
        'Olla Berlin - Lounge and Grill',
        'Diamond Lounge',
        'Marina Lounge',
        '100 Gramm Bar & Lounge',
        'Saphire Lounge',
        'BDSM Lounge Berlin',
        'Lale Cafe - Bar - Lounge',
        'Zaher''s Lounge - Café - Bar',
        'Relax Cafe-Bar-Lounge',
        'Captain Shisha Lounge',
        'Shisha-Bar Portakal',
        'KUMO Berlin Shisha Lounge',
        'Pavement Luxury Lounge',
        'Narquila Bar & Shisha Lounge',
        '111 Shisha Lounge',
        'The Sterling Tavern'
    )
)
INSERT INTO public.bar_themes (bar_id, theme_id)
SELECT ib.id, t.id
FROM inserted_bars ib
JOIN (VALUES
    ('One Lounge', 'cocktails'),
    ('Lufthansa Business Lounge', 'cocktails'),
    ('Kiss Lounge', 'cocktails'),
    ('DB Premium Lounge Berlin Hbf', 'cocktails'),
    ('Shadow Lounge', 'cocktails'),
    ('Balcone Lounge', 'cocktails'),
    ('Balcone Lounge', 'food'),
    ('Balcone Lounge', 'electronic'),
    ('The Vibe lounge women''s cafe', 'cocktails'),
    ('Noor Lounge - Shisha Bar Berlin', 'cocktails'),
    ('Mirror Lounge', 'cocktails'),
    ('Society Lounge', 'cocktails'),
    ('Luna Lounge Hookah&Restaurant', 'cocktails'),
    ('Luna Lounge Hookah&Restaurant', 'food'),
    ('Lobby Lounge & Bar Hotel Adlon', 'cocktails'),
    ('Lobby Lounge & Bar Hotel Adlon', 'food'),
    ('Lobby Lounge & Bar Hotel Adlon', 'electronic'),
    ('Zoé Lounge Berlin Hookah & Restaurant', 'cocktails'),
    ('Palm Lounge', 'cocktails'),
    ('Palm Lounge', 'food'),
    ('Diamond Bar - Café - Lounge', 'cocktails'),
    ('Bar Solut', 'cocktails'),
    ('Bar Solut', 'food'),
    ('Bar Solut', 'electronic'),
    ('Adara Lounge', 'cocktails'),
    ('Adara Lounge', 'food'),
    ('Adara Lounge', 'electronic'),
    ('Marrakesch Lounge & Bar nähe Alexanderplatz', 'cocktails'),
    ('King''s Lounge', 'cocktails'),
    ('Neelou Lounge', 'food'),
    ('Neelou Lounge', 'cocktails'),
    ('VIP Lounge Zeitgeist Right of way', 'cocktails'),
    ('VIP Lounge Zeitgeist Right of way', 'electronic'),
    ('Vikings Lounge', 'cocktails'),
    ('Karizma Lounge Berlin', 'cocktails'),
    ('GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte', 'cocktails'),
    ('GRAND BAR - Restaurant | Bar | Lounge | Event-Lokation in Berlin-Mitte', 'food'),
    ('The Lounge', 'cocktails'),
    ('Chill Out Bar', 'cocktails'),
    ('Chill Out Bar', 'electronic'),
    ('Coco Lounge', 'cocktails'),
    ('Loft14', 'cocktails'),
    ('The Leaf | Shisha Lounge Berlin', 'cocktails'),
    ('The Leaf | Shisha Lounge Berlin', 'food'),
    ('The Leaf | Shisha Lounge Berlin', 'spirits'),
    ('Hürrem Sultan Shisha & Cigar Bars', 'cocktails'),
    ('Hürrem Sultan Shisha & Cigar Bars', 'food'),
    ('Hürrem Sultan Shisha & Cigar Bars', 'electronic'),
    ('Hürrem Sultan Shisha & Cigar Bars', 'spirits'),
    ('Erks Lounge', 'cocktails'),
    ('Erks Lounge', 'electronic'),
    ('Bonjour Berlin Lounge', 'cocktails'),
    ('Bonjour Berlin Lounge', 'electronic'),
    ('Wodessa Lounge', 'cocktails'),
    ('Maza Lounge', 'cocktails'),
    ('Olla Berlin - Lounge and Grill', 'cocktails'),
    ('Olla Berlin - Lounge and Grill', 'food'),
    ('Diamond Lounge', 'cocktails'),
    ('Diamond Lounge', 'food'),
    ('Marina Lounge', 'cocktails'),
    ('Marina Lounge', 'food'),
    ('Marina Lounge', 'electronic'),
    ('100 Gramm Bar & Lounge', 'cocktails'),
    ('100 Gramm Bar & Lounge', 'food'),
    ('Saphire Lounge', 'cocktails'),
    ('Saphire Lounge', 'electronic'),
    ('BDSM Lounge Berlin', 'cocktails'),
    ('BDSM Lounge Berlin', 'electronic'),
    ('Lale Cafe - Bar - Lounge', 'food'),
    ('Lale Cafe - Bar - Lounge', 'cocktails'),
    ('Zaher''s Lounge - Café - Bar', 'cocktails'),
    ('Relax Cafe-Bar-Lounge', 'cocktails'),
    ('Relax Cafe-Bar-Lounge', 'food'),
    ('Relax Cafe-Bar-Lounge', 'spirits'),
    ('Captain Shisha Lounge', 'cocktails'),
    ('Shisha-Bar Portakal', 'cocktails'),
    ('Shisha-Bar Portakal', 'electronic'),
    ('KUMO Berlin Shisha Lounge', 'cocktails'),
    ('KUMO Berlin Shisha Lounge', 'food'),
    ('KUMO Berlin Shisha Lounge', 'electronic'),
    ('Pavement Luxury Lounge', 'cocktails'),
    ('Pavement Luxury Lounge', 'food'),
    ('Pavement Luxury Lounge', 'electronic'),
    ('Narquila Bar & Shisha Lounge', 'cocktails'),
    ('111 Shisha Lounge', 'cocktails'),
    ('The Sterling Tavern', 'cocktails'),
    ('The Sterling Tavern', 'food')
) AS bt(bar_name, theme_name) ON ib.name = bt.bar_name
JOIN public.themes t ON t.name = bt.theme_name;

COMMIT;

-- 批次 7: 记录 301-350
